### ISSUE TITLE
Add `charset` to `text/plain` responses

### ISSUE THREAD

**Issue by pbwolf** [clj-commons/aleph#236]
The README's HTTP server example

```
(defn handler [req]
  {:status 200
   :headers {"content-type" "text/plain"}
   :body "hello!"})
```

works because "hello!" consists of 7-bit Latin-1 characters.
Substitute "¡Hola!" and a problem emerges: the web browser displays
"Â¡Hola!".

The cause is a conflict between the Content-Type header and Aleph's
encoding of the response body.  Aleph serves the Content-Type as the
sample says, without a charset, which according to RFC2616 means
ISO-8859-1.[1] But Aleph encodes all String responses in UTF-8
regardless of the Content-Type.  Converting the code points to UTF-8
bytes and then interpreting the bytes as ISO-8859-1 results in the
spurious LATIN CAPITAL LETTER A WITH CIRCUMFLEX.

This behavior is unexpected because it corrupts the response message
in a way that is not required by the Ring SPEC [2].  True, SPEC does
not specify how the String should be encoded, but nor does it require
serving the headers exactly as given!  So a Ring-compliant server may
either make the body to suit the headers, or make the headers to suit
the body.

Ring's Jetty server obeys Content-Type's stated charset, with a
default of ISO-8859-1.  An alternative would be to force
"charset=utf-8" into the Content-Type when serving a String, if the
String is always going to be UTF-8.

[1] HTTP/1.1, RFC 2616, says:  When no explicit charset parameter is
provided by the sender, media subtypes of the "text" type are defined
to have a default charset value of "ISO-8859-1" when received via
HTTP. https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html

[2] https://github.com/ring-clojure/ring/blob/master/SPEC

**Comment by arnaudgeiser** [comment]
> The "charset" parameter is used with some media types to define the character set (section 3.4) of the data. When no explicit charset parameter is provided by the sender, media subtypes of the "text" type are defined to have a default charset value of "ISO-8859-1" when received via HTTP. Data in character sets other than "ISO-8859-1" or its subsets MUST be labeled with an appropriate charset value. See section [3.4.1](https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.4.1) for compatibility problems.

**Comment by KingMob** [comment]
The current RFC on the matter is https://www.rfc-editor.org/rfc/rfc6657.html.

And unfortunately, it's a little more complicated than it appears at first. For starters, the HTML RFCs are actually in disagreement on whether the default charset is US-ASCII or ISO-8859-1. RFC6657 defines the default to US-ASCII.

But more importantly, formats like HTML and XML can specify their charset internally, and internal charsets should take precedence over out-of-band charsets, and as a result, many user-agents/browsers _ignore_ the Content-type's charset for HTML/XML _anyway_.

I think for `text/plain` lilke the example above, the fix is straightforward, and we should add a `charset` to specify what it is. For `text/html` and `text/xml`, we may get it wrong (if we're not the ones generating the file), and it may be ignored in favor of in-band info regardless, so we should _not_ add a charset.

For all other `text/*` types, it should be up to the user to add the charset if necessary. For some `text/` MIME types it may be forbidden, so we can't add it _en masse_ without maintaining a table of MIME types and charset policies, which I'm not very interested in.
