### ISSUE TITLE
Support 3-arity async-ring

### ISSUE THREAD

**Issue by ikitommi** [clj-commons/aleph#439]
Would be great if there was a direct server option to run Aleph in the [ring-async](https://www.booleanknot.com/blog/2016/07/15/asynchronous-ring.html#compatability) mode, with 3 arities. Jetty ring adapter has [`:async?`](https://github.com/ring-clojure/ring/blob/master/ring-jetty-adapter/src/ring/adapter/jetty.clj#L132) option for this, maybe a new `:ring/async?` option in Aleph?

Seems to be a common question on how to run Aleph with ring-async, copy-pasting the needed glue-code is not very newbie-friendly. Also, not sure if the executor is set up correctly in the linked blog sample:

```clj
(defn ring->aleph [handler]
  (fn [request]
    (let [response (d/deferred)]
      (handler request #(d/success! response %) #(d/error! response %))
      response)))
```

**Comment by kachayev** [comment]
Maybe it's possible to use `:arglists` to check if we're dealing with async handler? 🤔

**Comment by ikitommi** [comment]
I think it's better to have an explicit option for this. Most (if not all) standard ring mw & helper functions support both arities. Deciding to go for 3-arity based on top-level arglist can fail with a ArityException at runtime from a user defined handler.

**Comment by ikitommi** [comment]
Sadly, one can't mix sync & async handlers with ring-async - middleware must call the next handler with the same arity. 

There are hybrid libs like [reitit](https://github.com/metosin/reitit) which allow 1-arity sync/async Interceptors to be used behind the top-level ring-async handler.

**Comment by kachayev** [comment]
Yeah, I see the logic and intuition in not having mixed style of execution. What I'm curious about... if you have a "truly" async middleware implemented let's say with `core.async`, - can you just plug it in with no worries about execution/pool/scheduling etc? Just because you have an API for doing that? All "standard" middleware from `ring-core` package seems to be synchronous despite async API they provide.

**Comment by ikitommi** [comment]
Yes. Or you could spin a thread on mw and sleep on it it before continuing... Haven't seen any guides on writing async-ring servers that don't crash under heavy load. 

If one would just use only Manifold (with Aleph) in async mw or in gandlee, using the system executioner would mean the thread pooling & backpressure should just work, right? Is there a way to force all user generated Deferreds to be executed in a Aleph-managed pool?

**Comment by kachayev** [comment]
No, I don't think that "thread pooling & backpressure should just work" is possible in any non-trivial application. My point is that you still need to think about it and adjust it to work within your environment and with your use cases. If you use deferred inside your middleware, it will, most probably, follow the same logic in terms of threading/pools as you set up for the entire server. Or you can use the same API with `onto`, `connect`, `with-executor` etc to change that in each particular middleware. Providing `ring` async API, as for me, makes an explicit statement that you might just drop in some middleware with async logic shredded inside and everything will still work as expected. 

My view on this topic might be biased as I've been working with Aleph for quite a long time now. It was always a bit annoying that you can't just use `ring-core`'s middlewares as far as they do not understand a deferred flowing around. So you need to take each one and tweak a bit to use `chain` or `let-flow` underneath. Fairly enough this fact mentioned in docs. 

Tho' I'm glad to hear any other opinions and thoughts on this matter!

**Comment by ztellman** [comment]
In the "default" configuration, users are supposed to be able to use blocking or non-blocking request handlers without having to think overly hard about execution models.  As Oleksii points out, at sufficient scale you can't safely ignore this, but for typical (read: low volume) use cases the Ring-async model should "just work".

I think I'd prefer to expose this as middleware in the `aleph.http` namespace rather than yet another option on `start-server`.  The snippet above, renamed to `wrap-ring-async-handler`, would be fine.  PRs welcome.

**Comment by kachayev** [comment]
@ztellman We have `aleph.http.client-middleware` namespace ported from `clj-http` and tailored to fit Aleph. Maybe we need to do the same for a server with `ring-core` middlewares?

**Comment by arnaudgeiser** [comment]
We forgot to close this issue.
There is an `aleph.http/wrap-ring-async-handler` available to turn a ring handler into an Aleph one. [1]

[1] : https://github.com/clj-commons/aleph/blob/master/src/aleph/http.clj#L436-L445
