### ISSUE TITLE
How do multipart requests work?

### ISSUE THREAD

**Issue by valerauko** [clj-commons/aleph#567]
I couldn't figure out how to handle incoming multipart requests on the server using the `decode-request` utility.

It seems that the stream gets closed as soon as the upload is done (which can be quite quick), which then calls `.destroy` on Netty's decoder, which in turn (I guess?) cleans up all the temp files, meaning none of the uploads are actually accessible in the handler.

Am I doing something wrong?

**Comment by valerauko** [comment]
I see. So for now using maybe the Apache multipart decoder (the ring-core multipart-params middleware) is the recommended way of dealing with uploads?

**Comment by arnaudgeiser** [comment]
For now, I would say there are three ways to handle multipart requests:

1. __Use the multipart-params middleware__
 
It's working as long as your body is an `java.io.InputStream`.
By default, every file is stored on the filesystem during 1 hour (configurable) [1]

An example:

```clojure
(require '[ring.middleware.multipart-params :refer [wrap-multipart-params]])

(defn handler [request]
  (let [params    (-> request :params)
        files     (vals params)
        tempfiles (map :tempfile files)]
    ;; do something with the `tempfiles`
    {:body "done!"}))

(aleph.http/start-server
 (wrap-multipart-params handler)
 {:port 8080})

@(http/post "http://localhost:8080" {:multipart [{:part-name "a file"
                                                  :content (io/file "test/file.txt")}]})

```

[1] : https://github.com/ring-clojure/ring/blob/master/ring-core/src/ring/middleware/multipart_params/temp_file.clj#L50-L51 


2. __Ensure the `decode-request` never use files__

This can be done by setting an infinite value for `memory-limit`.

```clojure
(require '[aleph.http.multipart :as multipart])

(defn handler [request]
  (let [chunks (multipart/decode-request request {:memory-limit Integer/MAX_VALUE})]
    (-> (d/loop []
          (d/chain' (s/take! chunks)
                    (fn [{:keys [content] :as chunk}]
                      (when (some? chunk)
                        ;; do something with the `content`
                        (d/recur)))))
        (d/chain'
         (fn [_]
           {:body "done!"})))))

(aleph.http/start-server handler {:port 8080})

@(http/post "http://localhost:8080" {:multipart [{:part-name "a file"
                                                  :content (io/file "test/file.txt")}]})
```

3. __Implement your own `decode-request`__

Some inspiration on the following PR : https://github.com/clj-commons/aleph/pull/596/files#diff-272a90e0af5e55488c08269c3ab128f28f2d63dcad30be761aca8c59cd0769c1R280-R346

## Personal advice

To be honest, unless your use case is really specific and you require a fine control over
the memory/disk usage :
- Direct Byte Buffer instead of an InputStream
- Very constrained in terms of storage

I would consider using [`multipart-params`](https://github.com/ring-clojure/ring/blob/master/ring-core/src/ring/middleware/multipart_params.clj) middleware

**Comment by valerauko** [comment]
The multipart-params middleware uses the apache-commons library underneath, which can be extremely inflexible when it comes to nonstandard headers (dealing with legacy clients etc)

**Comment by arnaudgeiser** [comment]
Fair enough.
I wasn't aware of the inflexibility of the multipart-params middleware.
On the current state of Aleph, that's the three solutions I have in mind.

Let's see what will happen with #596.
Otherwise, in your opinion, what would be the ideal API when working with Aleph/Netty?
Here are some ideas @kachayev had in mind when trying to improve the current situation. [1]

https://github.com/clj-commons/aleph/pull/432#issuecomment-449185986

**Comment by valerauko** [comment]
I think that the middleware as you suggest is the best option for now for most use-cases. Unless you have to deal with clients that the apache-commons lib just refuses to deal with, it works just fine.

Last I checked, netty's multipart upload handling was a pretty nasty mess that they wanted to remove/change, so not sure if it'd be wise to rely on in a "stable" thing like aleph.

There is the option of rolling aleph's own implementation based on netty primitives. It's probably quite a project, but considering how well clojure transducers might fit this problem it may be worth it.
