### ISSUE TITLE
Look into intermittently failing slow client test

### ISSUE THREAD

**Issue by KingMob** [clj-commons/aleph#626]
Discussion in #624.  

E.g.: https://app.circleci.com/pipelines/github/clj-commons/aleph/217/workflows/94f4080c-fe66-4712-beca-91ef7670c81d/jobs/212

It's happened at least twice in the same spot, which is suspicious. 

- [ ] Is there a regression? 
- [ ] Did CircleCI downgrade our test images? (unlikely)
- [ ] The idle timeout pipeline changed recently. 
- [ ] Could also be in manifold.
- [ ] Can we replicate locally?

Suggest bisection.

**Comment by DerGuteMoritz** [comment]
Good call on creating this ticket :+1:  Another case in point: https://app.circleci.com/pipelines/github/clj-commons/aleph/222/workflows/5dc5c892-5793-4ff6-ba4c-2b163d7d51bf/jobs/219

**Comment by KingMob** [comment]
It's the exact same subtest again. Hmm.

**Comment by DerGuteMoritz** [comment]
I've been running the test suite in a loop locally for a while now but so far was unable to reproduce it. Compared to [the Docker image the CI build uses](https://hub.docker.com/layers/circleci/clojure/lein-2.9.1/images/sha256-f0a076408fdf487adef2c31ce9ba2593b747cffc3e772fe32dfdad27b411e3f6?context=explore) I have slightly newer Leiningen (2.9.8) and OpenJDK (11.0.15) versions but I am doubtful that this is the cause :thinking:

**Comment by DerGuteMoritz** [comment]
OK after some fiddling I am now able to run the test suite in CircleCI's image locally with the same CPU and memory limits applied as the executor type these failed pipelines ran with (Medium). Let's see how it goes...

**Comment by DerGuteMoritz** [comment]
Oh wow, just after I had submitted this comment, the exact same failure happend! :tada: Let's see how reliable it is - gonna bisect then.

**Comment by DerGuteMoritz** [comment]
OK so I started bisecting at 6615edd84f6b4301e8c2eebb55af0613f6c1852d which is the merge commit of the PR which introduced the test in question (`test-idle-timeout`). I ended up at cfd65a8b1a860694a7be1c489ac0ce720c3363d2 as the (supposedly) first bad commit. It's only two commits in front of the first one and merely bumps the version and updates the changelog. Both seem pretty unlikely to cause this problem. Unsatisfied with the outcome, I went ahead and tried again with 6615edd84f6b4301e8c2eebb55af0613f6c1852d itself and after a few runs it failed the same way. Looks like it was flaky right off the bat but the flakiness might have become stronger since then. More recent commits seem to pretty much fail on the first try. Gotta step away from the computer now -- in the meantime, any thoughts on how to proceed with this?

Oh yeah, it's worth mentioning that it's sufficient to run `lein test :only aleph.http-test/test-idle-timeout` to make it fail so it doesn't seem to be some sort of overall test suite runtime effect. But as mentioned above, so far I was only able to make it fail when running it with the CircleCI Docker image.

**Comment by DerGuteMoritz** [comment]
Just dug into it a bit more and was able to pin it down to the `(bs/to-string body)` call in `echo-handler`: For whatever reason, it takes about thrice the time that `slow-stream` takes to produce all its values. At first I thought it must be caused by all the Aleph / Netty indirection but turns out it's even reproducible with bare `(bs/to-string (slow-stream))` which doesn't even involve Netty buffers! Given this test case:

```clojure
(deftest test-slow-stream
  (println "bs/to-string")
  (is (= "012345" (time (bs/to-string (slow-stream)))))
  (println "s/stream->seq")
  (is (= "012345" (time (apply str (s/stream->seq (slow-stream)))))))
``` 

Running it with `lein test :only aleph.http-test/test-slow-stream` via CircleCI's Docker image results in output like this:

```
bs/to-string
"Elapsed time: 983.259464 msecs"
s/stream->seq
"Elapsed time: 302.779341 msecs"
```

While running it outside Docker on my host machine:

```
bs/to-string
"Elapsed time: 304.501784 msecs"
s/stream->seq
"Elapsed time: 302.249939 msecs"
```

I also just tried with [this image](https://hub.docker.com/layers/circleci/clojure/openjdk-11-lein-2.9.8/images/sha256-fb17fd971955769ad3f2ad8da7b43b74c19aedb8a89243a2dc1afac134456dac?context=explore) which has more recent versions of Leiningen (2.9.8) and OpenJDK (11.0.13) but same results. :thinking:

**Comment by DerGuteMoritz** [comment]
Hmm just thought this could be caused by how `clj-common.byte-streams` works internally: It has to construct the conversion path on the first invocation for this particular combination of types. And indeed, changing the test to call `bs/to-string` twice like this:

```clojure
(deftest test-slow-stream
  (println "bs/to-string")
  (is (= "012345" (time (bs/to-string (slow-stream)))))
  (is (= "012345" (time (bs/to-string (slow-stream))))))
```

Shows that the second call is fast:

```
bs/to-string
"Elapsed time: 1078.81082 msecs"
"Elapsed time: 306.38677 msecs"
```

The non-Docker measurement in my previous comment actually was skewed because I ran it from within a REPL which already had that conversion path memoized. However, running it cold on the host still results in a much smaller difference:

```
bs/to-string
"Elapsed time: 321.50442 msecs"
"Elapsed time: 305.597864 msecs"
```

So the next question is: Why would constructing the conversion path be that much slower in Docker? :thinking:

**Comment by DerGuteMoritz** [comment]
New insights:

1. The slowness comes from `clj-commons.byte-streams/stream-converter` which is invoked from `to-string` via `convert`. This function is memoized so only the first call pays the cost.
2. Running `aleph.http-test` with a debug log added to `stream-converter` shows that the call in `test-idle-timeout` is indeed the first one here.
3. When running the whole test suite, I *think* the order in which test namespaces are run is non-deterministic. Maybe there is another namespace which hits this conversion, too. If that one ends up running before `aleph.http-test`, the test would not fail. That would explain the flakiness we see.

**Comment by KingMob** [comment]
Good detective work! I'm not exactly sure why it would be slower in Docker, other than I assume the free machines Circle gives us are underpowered compared to our dev machines.

Maybe the solution is to warm up the byte-streams conversion graph.

**Comment by DerGuteMoritz** [comment]
> I'm not exactly sure why it would be slower in Docker, other than I assume the free machines Circle gives us are underpowered compared to our dev machines.

Right, that seems to be it: Running the image in a container with 6 CPUs rather than 2 (which is what CircleCI gives us), I get pretty much the same measurements as on my host machine. 
 
> Maybe the solution is to warm up the byte-streams conversion graph.

Heh, great minds think alike :+1:
